/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.joyeria.joyeriamvc.view.inventario;

import com.joyeria.joyeriamvc.model.vo.JoyaVO;
import com.joyeria.joyeriamvc.view.AbstractPanel;
import java.util.Comparator;
import java.util.List;
import javax.swing.InputVerifier;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hfria
 */
public class InventarioJoyasView extends AbstractPanel {

    public JButton getBtnExportCSV() {
        return btnExportCSV;
    }

    /**
     * Creates new form InventarioJoyasView
     */
    public InventarioJoyasView() {
        initComponents();
        customComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputMaterial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputWeight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnModificarJoya = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputPrice = new javax.swing.JTextField();
        btnEliminarJoya = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventarioJoyas = new javax.swing.JTable();
        btnActualizarTablaJoya = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExportCSV = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        inputStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Stock");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Material");

        inputMaterial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Peso (gr)");

        inputWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Inventario Joyas");

        btnModificarJoya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificarJoya.setText("Modificar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        inputName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Precio");

        inputPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnEliminarJoya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminarJoya.setText("Eliminar");

        tablaInventarioJoyas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Material", "Peso (gr)", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInventarioJoyas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaInventarioJoyas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInventarioJoyasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInventarioJoyas);
        tablaInventarioJoyas.getAccessibleContext().setAccessibleName("tablaInventarioJoyas");

        btnActualizarTablaJoya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnActualizarTablaJoya.setText("Actualizar tabla");

        btnBack.setText("Atrás");

        btnExportCSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExportCSV.setText("Exportar a .xlsx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(btnActualizarTablaJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputWeight)
                    .addComponent(inputMaterial)
                    .addComponent(inputStock)
                    .addComponent(inputPrice)
                    .addComponent(inputName)
                    .addComponent(btnModificarJoya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualizarTablaJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExportCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        btnModificarJoya.getAccessibleContext().setAccessibleName("btnModificarJoya");
        btnEliminarJoya.getAccessibleContext().setAccessibleName("btnEliminarJoya");
        btnActualizarTablaJoya.getAccessibleContext().setAccessibleName("btnActualizarTablaJoya");
        btnBack.getAccessibleContext().setAccessibleName("btnBack");
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBack() {
        return btnBack;
    }

    private void tablaInventarioJoyasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioJoyasMouseClicked
        int rowIndex = tablaInventarioJoyas.getSelectedRow();
        inputName.setText(tablaInventarioJoyas.getValueAt(rowIndex, 1).toString());
        inputMaterial.setText(tablaInventarioJoyas.getValueAt(rowIndex, 2).toString());
        inputWeight.setText(tablaInventarioJoyas.getValueAt(rowIndex, 3).toString());
        inputPrice.setText(tablaInventarioJoyas.getValueAt(rowIndex, 4).toString());
        inputStock.setText(tablaInventarioJoyas.getValueAt(rowIndex, 5).toString());
    }//GEN-LAST:event_tablaInventarioJoyasMouseClicked
//nombre material peso precio stock

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTablaJoya;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEliminarJoya;
    private javax.swing.JButton btnExportCSV;
    private javax.swing.JButton btnModificarJoya;
    private javax.swing.JTextField inputMaterial;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JTextField inputStock;
    private javax.swing.JTextField inputWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInventarioJoyas;
    // End of variables declaration//GEN-END:variables

    public JTable getTablaInventarioJoyas() {
        return tablaInventarioJoyas;
    }

    public JButton getBtnActualizarTablaJoya() {
        return btnActualizarTablaJoya;
    }

    public JButton getBtnEliminarJoya() {
        return btnEliminarJoya;
    }

    public JButton getBtnModificarJoya() {
        return btnModificarJoya;
    }

    public JTextField getInputMaterial() {
        return inputMaterial;
    }

    public JTextField getInputName() {
        return inputName;
    }

    public JTextField getInputPrice() {
        return inputPrice;
    }

    public JTextField getInputStock() {
        return inputStock;
    }

    public JTextField getInputWeight() {
        return inputWeight;
    }

    public void updateTable(List<JoyaVO> joyas) {
        DefaultTableModel tableModel = (DefaultTableModel) tablaInventarioJoyas.getModel();
        tableModel.setRowCount(0);
        for (JoyaVO joya : joyas) {
            tableModel.addRow(new Object[]{
                joya.getId(),
                joya.getName(),
                joya.getMaterial(),
                joya.getWeight_gr(),
                joya.getPrice(),
                joya.getStock()
            });

        }
        tableModel.fireTableDataChanged();
    }

    private void customComponents() {
        TableColumn column;
        column = tablaInventarioJoyas.getColumnModel().getColumn(0);
        column.setPreferredWidth(60);

        column = tablaInventarioJoyas.getColumnModel().getColumn(5);
        column.setPreferredWidth(48);

        column = tablaInventarioJoyas.getColumnModel().getColumn(1);
        column.setPreferredWidth(123);

        column = tablaInventarioJoyas.getColumnModel().getColumn(2);
        column.setPreferredWidth(123);

        column = tablaInventarioJoyas.getColumnModel().getColumn(3);
        column.setPreferredWidth(123);

        column = tablaInventarioJoyas.getColumnModel().getColumn(4);
        column.setPreferredWidth(123);

        DefaultTableModel tableModel = (DefaultTableModel) tablaInventarioJoyas.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel);
        tablaInventarioJoyas.setRowSorter(sorter);
        sorter.setComparator(0, Comparator.comparingInt(o -> (int) o));
        sorter.setComparator(4, Comparator.comparingLong(o -> (Long) o));
        sorter.setComparator(5, Comparator.comparingInt(o -> (int) o));
        sorter.setComparator(3, new Comparator<Object>() {
            @Override
            public int compare(Object o1, Object o2) {
                if (o1 instanceof Float && o2 instanceof Float) {
                    return Float.compare((Float) o1, (Float) o2);
                }
                return 0; // Fallback for non-Float values
            }
        });
        
        inputPrice.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                boolean match = text.matches("\\d*");
                if (!match) {
                    JOptionPane.showMessageDialog(null, "Solo se admiten números positivos");
                }
                return match;
            }
        });
        inputStock.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                boolean match = text.matches("\\d*");
                if (!match) {
                    JOptionPane.showMessageDialog(null, "Solo se admiten números positivos");
                }
                return match;
            }
        });
        inputWeight.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                boolean match = text.matches("\\d*|\\d+\\.\\d*");
                if (!match) {
                    JOptionPane.showMessageDialog(null, "Solo se admiten números decimales positivos");
                }
                return match;
            }
        });

    }

    public int getSelectedJoyaId() {
        int rowIndex = tablaInventarioJoyas.getSelectedRow();
        if (rowIndex == -1) {
            return -1;
        }
        return (int) tablaInventarioJoyas.getValueAt(rowIndex, 0);

    }

    public void clearTablaJoyas() {
        DefaultTableModel tableModel = (DefaultTableModel) tablaInventarioJoyas.getModel();
        tableModel.setRowCount(0);
    }

    public void clearInputFields() {
        inputName.setText(null);
        inputMaterial.setText(null);
        inputWeight.setText(null);
        inputPrice.setText(null);
        inputStock.setText(null);
    }
}
