/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.joyeria.joyeriamvc.view.inventario;

import com.joyeria.joyeriamvc.view.*;
import javax.swing.JButton;

/**
 *
 * @author hfria
 */
public class InventarioMenuView extends AbstractPanel {
    /**
     * Creates new form MainMenu
     */
    public InventarioMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnToIngresarJoya = new javax.swing.JButton();
        btnToInventarioJoyas = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Inventario");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 140, 40));

        btnToIngresarJoya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToIngresarJoya.setText("Ingresar Joya");
        add(btnToIngresarJoya, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, 80));
        btnToIngresarJoya.getAccessibleContext().setAccessibleName("btnToIngresarJoya");

        btnToInventarioJoyas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToInventarioJoyas.setText("Inventario Joyas");
        add(btnToInventarioJoyas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 180, 80));
        btnToInventarioJoyas.getAccessibleContext().setAccessibleName("btnToInventarioJoyas");

        btnBack.setText("Atrás");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        btnBack.getAccessibleContext().setAccessibleName("btnBack");
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBack() {
        return btnBack;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnToIngresarJoya;
    private javax.swing.JButton btnToInventarioJoyas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnToInventarioJoyas() {
        return btnToInventarioJoyas;
    }

    public JButton getBtnToIngresarJoya() {
        return btnToIngresarJoya;
    }

    
    
}
