/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.joyeria.joyeriamvc.view.venta;

import com.joyeria.joyeriamvc.model.vo.ClienteVO;
import com.joyeria.joyeriamvc.model.vo.JoyaVO;
import com.joyeria.joyeriamvc.view.AbstractPanel;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.InputVerifier;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author hfria
 */
public class RealizarVentaView extends AbstractPanel {

    /**
     * Creates new form RealizarVentaView
     */
    public RealizarVentaView() {
        initComponents();
        customComponents();
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxJoya = new javax.swing.JComboBox<>();
        comboBoxCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosJoya = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosCliente = new javax.swing.JTable();
        btnConfirmarVenta = new javax.swing.JButton();
        btnActualizarDatos = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Realizar venta");

        comboBoxJoya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxJoyaActionPerformed(evt);
            }
        });

        comboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Joya");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad");

        inputCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        datosJoya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Material", "Peso (gr)", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        datosJoya.setAutoscrolls(false);
        jScrollPane1.setViewportView(datosJoya);
        datosJoya.getAccessibleContext().setAccessibleName("datosJoya");

        datosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        datosCliente.setAutoscrolls(false);
        jScrollPane2.setViewportView(datosCliente);
        datosCliente.getAccessibleContext().setAccessibleName("datosCliente");

        btnConfirmarVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmarVenta.setText("Confirmar Venta");

        btnActualizarDatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnActualizarDatos.setText("Actualizar");

        btnBack.setText("Atrás");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(btnBack))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActualizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmarVenta))
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(comboBoxJoya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(765, 765, 765))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxJoya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );

        comboBoxJoya.getAccessibleContext().setAccessibleName("comboBoxJoya");
        comboBoxCliente.getAccessibleContext().setAccessibleName("comboBoxCliente");
        inputCantidad.getAccessibleContext().setAccessibleName("inputCantidad");
        btnConfirmarVenta.getAccessibleContext().setAccessibleName("btnConfirmarVenta");
        btnActualizarDatos.getAccessibleContext().setAccessibleName("btnActualizarDatos");
        btnBack.getAccessibleContext().setAccessibleName("btnBack");
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxJoyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxJoyaActionPerformed
        fillTablaJoya();
    }//GEN-LAST:event_comboBoxJoyaActionPerformed

    private void comboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxClienteActionPerformed
        fillTablaCliente();
    }//GEN-LAST:event_comboBoxClienteActionPerformed

    public JButton getBtnConfirmarVenta() {
        return btnConfirmarVenta;
    }

    public JTextField getInputCantidad() {
        return inputCantidad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDatos;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JComboBox<ClienteVO> comboBoxCliente;
    private javax.swing.JComboBox<JoyaVO> comboBoxJoya;
    private javax.swing.JTable datosCliente;
    private javax.swing.JTable datosJoya;
    private javax.swing.JTextField inputCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void customComponents() {
        TableColumn column;
        column = datosCliente.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);

        column = datosCliente.getColumnModel().getColumn(1);
        column.setPreferredWidth(500);

        column = datosJoya.getColumnModel().getColumn(0);
        column.setPreferredWidth(60);

        column = datosJoya.getColumnModel().getColumn(5);
        column.setPreferredWidth(48);

        column = datosJoya.getColumnModel().getColumn(1);
        column.setPreferredWidth(123);

        column = datosJoya.getColumnModel().getColumn(2);
        column.setPreferredWidth(123);

        column = datosJoya.getColumnModel().getColumn(3);
        column.setPreferredWidth(123);

        column = datosJoya.getColumnModel().getColumn(4);
        column.setPreferredWidth(123);

        comboBoxCliente.setRenderer(new customRenderer());
        comboBoxJoya.setRenderer(new customRenderer());

        inputCantidad.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                boolean match = text.matches("-?\\d*");

                if (!match) {
                    JOptionPane.showMessageDialog(null, "Solo se admiten dígitos");
                }
                return match;
            }
        });

    }

    public JButton getBtnActualizarDatos() {
        return btnActualizarDatos;
    }

    public void fillComboBoxCliente(List<ClienteVO> clientes) {
        comboBoxCliente.removeAllItems();
        for (ClienteVO cliente : clientes) {
            comboBoxCliente.addItem(cliente);
        }
        comboBoxCliente.setSelectedIndex(-1);
    }

    public void fillComboBoxJoya(List<JoyaVO> joyas) {
        comboBoxJoya.removeAllItems();
        for (JoyaVO joya : joyas) {
            comboBoxJoya.addItem(joya);
        }
        comboBoxJoya.setSelectedIndex(-1);
    }

    private void fillTablaJoya() {
        DefaultTableModel tableModel = (DefaultTableModel) datosJoya.getModel();
        tableModel.setRowCount(0);
        JoyaVO joya = (JoyaVO) comboBoxJoya.getSelectedItem();
        if (joya == null) {
            return;
        }
        tableModel.addRow(new Object[]{
            joya.getId(),
            joya.getName(),
            joya.getMaterial(),
            joya.getWeight_gr(),
            joya.getPrice(),
            joya.getStock()
        });
        tableModel.fireTableDataChanged();
    }

    public JComboBox<ClienteVO> getComboBoxCliente() {
        return comboBoxCliente;
    }

    public JComboBox<JoyaVO> getComboBoxJoya() {
        return comboBoxJoya;
    }

    private void fillTablaCliente() {
        DefaultTableModel tableModel = (DefaultTableModel) datosCliente.getModel();
        tableModel.setRowCount(0);
        ClienteVO cliente = (ClienteVO) comboBoxCliente.getSelectedItem();
        if (cliente == null) {
            return;
        }
        tableModel.addRow(new Object[]{
            cliente.getId(),
            cliente.getName()
        });
        tableModel.fireTableDataChanged();
    }

    class customRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if (value instanceof JoyaVO) {
                JoyaVO joya = (JoyaVO) value;
                setText(joya.getName());
            }
            if (value instanceof ClienteVO) {
                ClienteVO cliente = (ClienteVO) value;
                setText(cliente.getName());
            }

            return this;
        }
    }

}
