/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.joyeria.joyeriamvc.view.venta;

import com.joyeria.joyeriamvc.view.*;

import javax.swing.JButton;

/**
 *
 * @author hfria
 */
public class VentasMenuView extends AbstractPanel {
    /**
     * Creates new form MainMenu
     */
    public VentasMenuView() {
        initComponents();
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRealizarVenta = new javax.swing.JButton();
        btnReporteBasicoVentas = new javax.swing.JButton();
        btnReporteVentas = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ventas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 140, 40));

        btnRealizarVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRealizarVenta.setText("Realizar Venta");
        add(btnRealizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, 80));
        btnRealizarVenta.getAccessibleContext().setAccessibleName("btnRealizarVenta");

        btnReporteBasicoVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReporteBasicoVentas.setText("Reporte Basico Ventas");
        add(btnReporteBasicoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 220, 80));
        btnReporteBasicoVentas.getAccessibleContext().setAccessibleName("btnReporteVentas");

        btnReporteVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReporteVentas.setText("Reporte Ventas");
        add(btnReporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 220, 80));
        btnReporteVentas.getAccessibleContext().setAccessibleName("btnReporteVentas");

        btnBack.setText("Atrás");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        btnBack.getAccessibleContext().setAccessibleName("btnBack");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRealizarVenta;
    private javax.swing.JButton btnReporteBasicoVentas;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnReporteBasicoVentas() {
        return btnReporteBasicoVentas;
    }

    public JButton getBtnRealizarVenta() {
        return btnRealizarVenta;
    }

    public JButton getBtnReporteVentas() {
        return btnReporteVentas;
    }

    
    
}
