/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.joyeria.joyeriamvc.view;

import com.joyeria.joyeriamvc.view.inventario.IngresarJoyaView;
import com.joyeria.joyeriamvc.view.inventario.InventarioJoyasView;
import com.joyeria.joyeriamvc.view.inventario.InventarioMenuView;
import com.joyeria.joyeriamvc.view.venta.RealizarVentaView;
import com.joyeria.joyeriamvc.view.venta.ReporteBasicoVentasView;
import com.joyeria.joyeriamvc.view.venta.ReporteVentasView;
import com.joyeria.joyeriamvc.view.venta.VentasMenuView;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author hfria
 */
public class AplicationFrame extends javax.swing.JFrame {

    public AplicationFrame() {
        initComponents();
        setupCustomPanels();

        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    public ReporteBasicoVentasView getReporteBasicoVentasView() {
        return reporteBasicoVentasView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCambiante = new javax.swing.JPanel();
        mainMenu = new com.joyeria.joyeriamvc.view.MainMenuView();
        ventasMenuView = new com.joyeria.joyeriamvc.view.venta.VentasMenuView();
        inventarioMenuView = new com.joyeria.joyeriamvc.view.inventario.InventarioMenuView();
        ingresarJoyaView = new com.joyeria.joyeriamvc.view.inventario.IngresarJoyaView();
        inventarioJoyasView = new com.joyeria.joyeriamvc.view.inventario.InventarioJoyasView();
        realizarVentaView = new com.joyeria.joyeriamvc.view.venta.RealizarVentaView();
        reporteVentasView = new com.joyeria.joyeriamvc.view.venta.ReporteVentasView();
        reporteBasicoVentasView = new com.joyeria.joyeriamvc.view.venta.ReporteBasicoVentasView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCambiante.setPreferredSize(new java.awt.Dimension(1000, 600));
        panelCambiante.setLayout(new java.awt.CardLayout());
        panelCambiante.add(mainMenu, "mainMenu");
        panelCambiante.add(ventasMenuView, "ventasMenuView");
        panelCambiante.add(inventarioMenuView, "inventarioMenuView");
        panelCambiante.add(ingresarJoyaView, "ingresarJoyaView");
        panelCambiante.add(inventarioJoyasView, "inventarioJoyasView");
        panelCambiante.add(realizarVentaView, "realizarVentaView");
        panelCambiante.add(reporteVentasView, "reporteVentasView");
        panelCambiante.add(reporteBasicoVentasView, "reporteBasicoVentasView");

        getContentPane().add(panelCambiante, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    public RealizarVentaView getRealizarVentaView() {
        return realizarVentaView;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.joyeria.joyeriamvc.view.inventario.IngresarJoyaView ingresarJoyaView;
    private com.joyeria.joyeriamvc.view.inventario.InventarioJoyasView inventarioJoyasView;
    private com.joyeria.joyeriamvc.view.inventario.InventarioMenuView inventarioMenuView;
    private com.joyeria.joyeriamvc.view.MainMenuView mainMenu;
    private javax.swing.JPanel panelCambiante;
    private com.joyeria.joyeriamvc.view.venta.RealizarVentaView realizarVentaView;
    private com.joyeria.joyeriamvc.view.venta.ReporteBasicoVentasView reporteBasicoVentasView;
    private com.joyeria.joyeriamvc.view.venta.ReporteVentasView reporteVentasView;
    private com.joyeria.joyeriamvc.view.venta.VentasMenuView ventasMenuView;
    // End of variables declaration//GEN-END:variables

    private void setupCustomPanels() {
        CardLayout cardLayout = (CardLayout) panelCambiante.getLayout();
        inventarioMenuView.setParentComponents(panelCambiante, cardLayout);
        ventasMenuView.setParentComponents(panelCambiante, cardLayout);
        mainMenu.setParentComponents(panelCambiante, cardLayout);
        inventarioMenuView.setParentComponents(panelCambiante, cardLayout);
        cardLayout.show(panelCambiante, "mainMenu");

    }

    public MainMenuView getMainMenuPanel() {
        return mainMenu;
    }

    public JPanel getPanelCambiante() {
        return panelCambiante;
    }
    
    public void changePanelView(String panelName){
        CardLayout cardLayout = (CardLayout) panelCambiante.getLayout();
        cardLayout.show(panelCambiante, panelName);
    }

    public InventarioMenuView getInventarioMenuView() {
        return inventarioMenuView;
    }

    public VentasMenuView getVentasMenuView() {
        return ventasMenuView;
    }

    public IngresarJoyaView getIngresarJoyaView() {
        return ingresarJoyaView;
    }

    public InventarioJoyasView getInventarioJoyasView() {
        return inventarioJoyasView;
    }

    public ReporteVentasView getReporteVentasView() {
        return reporteVentasView;
    }
    

}
