/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.joyeria.joyeriamvc.view;

import javax.swing.JButton;

/**
 *
 * @author hfria
 */
public class MainMenuView extends AbstractPanel {
    /**
     * Creates new form MainMenu
     */
    public MainMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Sistema de Inventario y Ventas de Joyería");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 470, 40));

        btnVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVentas.setText("Ventas");
        add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, 80));
        btnVentas.getAccessibleContext().setAccessibleName("btnVentas");

        btnInventario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInventario.setText("Inventario");
        add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 180, 80));
        btnInventario.getAccessibleContext().setAccessibleName("btnInventario");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnInventario() {
        return btnInventario;
    }

    public JButton getBtnVentas() {
        return btnVentas;
    }

    
    
}
